name: foodfinder
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.18.0
  firebase_database: ^10.2.1
  geolocator: ^9.0.2
  flutter_local_notifications: ^19.0.0
  timezone: ^0.10.0
  cupertino_icons: ^1.0.8
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
